
import { Property } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern 5 Bedroom Fully Detached Mansion',
    type: 'For Sale',
    category: 'House',
    price: 280000000,
    currency: '₦',
    location: 'Banana Island, Lagos',
    beds: 5,
    baths: 5,
    toilets: 6,
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
    featured: true,
    postedDate: '1 hour ago',
    sqm: 1200,
    description: 'This architectural masterpiece offers unparalleled luxury in the heart of Banana Island. Features floor-to-ceiling windows, a private infinity pool, and high-end finishes throughout. Designed for those who appreciate the finer things in life.',
    interiorFeatures: ['Smart Home Automation', 'Walk-in Closets', 'Chef\'s Kitchen', 'Marble Flooring', 'Home Cinema', 'Elevator'],
    amenities: ['24/7 Power', 'Gym', 'Swimming Pool', 'Fenced Backyard', 'CCTV', 'Underground Parking']
  },
  {
    id: '2',
    title: 'Luxury 3 Bedroom Waterfront Apartment',
    type: 'To Rent',
    category: 'Flat',
    price: 8500000,
    currency: '₦',
    location: 'Eko Atlantic, Victoria Island',
    beds: 3,
    baths: 3,
    toilets: 4,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    featured: true,
    postedDate: '4 hours ago',
    sqm: 350,
    description: 'Experience living in the city of the future. This apartment offers stunning ocean views and state-of-the-art infrastructure in Nigeria\'s most prestigious development. Fully serviced and highly secure.',
    interiorFeatures: ['Central Air Conditioning', 'Imported Kitchen Fittings', 'High Ceilings', 'Panoramic Windows'],
    amenities: ['Underground Parking', 'High-Speed Elevators', 'Intercom System', 'Concierge Service']
  },
  {
    id: '3',
    title: 'Prime Industrial Land (5000sqm)',
    type: 'For Sale',
    category: 'Land',
    price: 450000000,
    currency: '₦',
    location: 'Agbara Industrial Estate, Ogun',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80',
    featured: false,
    postedDate: '12 hours ago',
    sqm: 5000,
    description: 'Strategically located plot of industrial land, perfect for large-scale manufacturing or warehousing. Excellent road access and proximity to established industrial giants.',
    amenities: ['Perimeter Fencing', 'Electricity Connection Ready', 'Approved Survey Plan', 'Industrial Zone']
  },
  {
    id: '4',
    title: 'Executive 4 Bedroom Semi-Detached Duplex',
    type: 'For Sale',
    category: 'House',
    price: 120000000,
    currency: '₦',
    location: 'Maitama, Abuja',
    beds: 4,
    baths: 4,
    toilets: 5,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    featured: true,
    postedDate: '1 day ago',
    sqm: 650,
    description: 'A beautifully crafted semi-detached duplex in the upscale neighborhood of Maitama. Offers spacious living areas, a modern kitchen, and an ample parking space for up to 4 cars.',
    interiorFeatures: ['POP Ceiling', 'Tiled Floors', 'Wardrobes', 'Inverter System', 'Pantry'],
    amenities: ['Gated Community', 'Armed Guard Presence', 'Constant Water Supply', 'Playground']
  },
  {
    id: '5',
    title: 'Contemporary 2 Bedroom Serviced Flat',
    type: 'To Rent',
    category: 'Flat',
    price: 4000000,
    currency: '₦',
    location: 'Old Ikoyi, Lagos',
    beds: 2,
    baths: 2,
    toilets: 3,
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
    featured: false,
    postedDate: '2 days ago',
    sqm: 180,
    description: 'Serviced luxury flat located in the serene environment of Old Ikoyi. Perfect for young professionals seeking comfort and proximity to the business district.',
    interiorFeatures: ['Fully Fitted Kitchen', 'Bathtub', 'Balcony', 'Smoke Detectors'],
    amenities: ['Standby Generator', 'Cleaning Services', 'Uniformed Security', 'Swimming Pool']
  },
  {
    id: '6',
    title: 'Residential Land in Gated Community',
    type: 'For Sale',
    category: 'Land',
    price: 35000000,
    currency: '₦',
    location: 'Ibeju-Lekki, Lagos',
    imageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=800&q=80',
    featured: true,
    postedDate: '3 days ago',
    sqm: 600,
    description: 'Secure your future with this dry, residential land in a fast-developing part of Ibeju-Lekki. Ideal for building your dream family home or as a high-ROI investment.',
    amenities: ['Global C of O', 'Drainage System', 'Paved Roads', 'Street Lights']
  },
  {
    id: '7',
    title: 'Luxury 4 Bedroom Terrace in Lekki Phase 1',
    type: 'For Sale',
    category: 'House',
    price: 95000000,
    currency: '₦',
    location: 'Lekki Phase 1, Lagos',
    beds: 4,
    baths: 4,
    toilets: 5,
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
    featured: true,
    postedDate: '2 hours ago',
    sqm: 450,
    description: 'Modern terrace house in a highly sought-after location. Features an open-plan living area, fitted kitchen, and a private backyard.',
    interiorFeatures: ['In-built Speakers', 'Jacuzzi', 'Gas Cooker', 'Heat Extractor'],
    amenities: ['Treated Water', 'Estate Security', 'Visitor Parking']
  },
  {
    id: '8',
    title: 'Prime Commercial Plaza Space',
    type: 'To Rent',
    category: 'Commercial',
    price: 15000000,
    currency: '₦',
    location: 'Wuse 2, Abuja',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    featured: false,
    postedDate: '5 hours ago',
    sqm: 250,
    description: 'Ground floor retail space in a busy commercial hub. Perfect for a showroom, banking hall, or corporate office.',
    amenities: ['High Visibility', 'Security Post', 'Central Air System']
  },
  {
    id: '9',
    title: 'Charming 4 Bedroom Bungalow',
    type: 'For Sale',
    category: 'House',
    price: 65000000,
    currency: '₦',
    location: 'GRA, Port Harcourt',
    beds: 4,
    baths: 4,
    toilets: 5,
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    featured: false,
    postedDate: '1 day ago',
    sqm: 800,
    description: 'Spacious bungalow with a large compound in the secure GRA neighborhood. Excellent for a family looking for privacy and space.',
    interiorFeatures: ['Tiled Floors', 'Wardrobes', 'Kitchen Cabinet'],
    amenities: ['Borehole', 'Security Gate', 'Ample Parking']
  }
];

export const LOCATIONS = [
  'Lagos', 'Abuja', 'Rivers', 'Oyo', 'Ogun', 'Enugu', 'Edo', 'Delta'
];

export const CATEGORIES = [
  'House', 'Flat / Apartment', 'Land', 'Commercial Property'
];
